using System.Text;
using TorVpnForWindows.Config;

namespace TorVpnForWindows.Core;

/// <summary>
/// Ports and address ranges a session uses. Resolved once per connect so a port already taken by,
/// for example, a running Tor Browser does not break the session.
/// </summary>
public sealed record SessionEndpoints(int SocksPort, int DnsPort, int ControlPort)
{
    /// <summary>
    /// Range Tor hands out for names it maps locally, above all .onion addresses.
    ///
    /// It has to be routable through the TUN, which rules out Tor's loopback default of
    /// 127.192.0.0/10. It also has to stay outside RFC 1918 space, because those ranges are
    /// excluded from the tunnel when the user allows local network access. 198.18.0.0/15 is
    /// reserved for benchmarking and is not used on real networks.
    /// </summary>
    public const string OnionMapRange = "198.18.0.0/15";
}

public static class TorRcBuilder
{
    public static string Build(
        AppSettings settings,
        SessionEndpoints endpoints,
        IReadOnlyList<string> bridges,
        string lyrebirdPath)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by Tor VPN for Windows. Edits are overwritten on every connect.");
        sb.AppendLine();

        sb.AppendLine($"DataDirectory {Quote(AppPaths.TorData)}");
        sb.AppendLine($"GeoIPFile {Quote(AppPaths.GeoIpFile)}");
        sb.AppendLine($"GeoIPv6File {Quote(AppPaths.GeoIpV6File)}");
        sb.AppendLine();

        sb.AppendLine("# This process is a client only; it never acts as a relay.");
        sb.AppendLine("ClientOnly 1");
        sb.AppendLine("AvoidDiskWrites 1");
        sb.AppendLine("Log notice stdout");
        sb.AppendLine();

        sb.AppendLine("# sing-box hands TCP connections to this SOCKS port and DNS queries to DNSPort.");
        sb.AppendLine($"SocksPort 127.0.0.1:{endpoints.SocksPort} IPv6Traffic");
        sb.AppendLine($"DNSPort 127.0.0.1:{endpoints.DnsPort}");
        sb.AppendLine("SocksPolicy accept 127.0.0.0/8");
        sb.AppendLine("SocksPolicy reject *");
        sb.AppendLine();

        sb.AppendLine($"ControlPort 127.0.0.1:{endpoints.ControlPort}");
        sb.AppendLine("CookieAuthentication 1");
        sb.AppendLine();

        sb.AppendLine("# Resolve .onion names to addresses inside a routable range so the tunnel can");
        sb.AppendLine("# carry them back to Tor, which maps them to the hidden service.");
        sb.AppendLine("AutomapHostsOnResolve 1");
        sb.AppendLine("AutomapHostsSuffixes .onion,.exit");
        sb.AppendLine($"VirtualAddrNetworkIPv4 {SessionEndpoints.OnionMapRange}");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(settings.ExitCountry))
        {
            sb.AppendLine("# Exit country chosen by the user.");
            sb.AppendLine($"ExitNodes {{{settings.ExitCountry}}}");
            sb.AppendLine("StrictNodes 1");
            sb.AppendLine();
        }

        if (bridges.Count > 0)
        {
            var exec = ExecutablePathForTor(lyrebirdPath);

            sb.AppendLine("# Bridges hide the fact that Tor is in use from an observer on the local network.");
            sb.AppendLine("UseBridges 1");
            sb.AppendLine($"ClientTransportPlugin meek_lite,obfs2,obfs3,obfs4,scramblesuit,webtunnel exec {exec}");
            sb.AppendLine($"ClientTransportPlugin snowflake exec {exec}");

            foreach (var bridge in bridges)
            {
                sb.AppendLine($"Bridge {bridge}");
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// Wraps a path in the quoted form Tor's configuration parser understands, so a user name with
    /// a space in it does not break the file.
    /// </summary>
    private static string Quote(string path) =>
        "\"" + path.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    /// <summary>
    /// ClientTransportPlugin splits its exec argument on whitespace, so a path containing a space
    /// would be read as a program plus arguments. The 8.3 short form has no spaces and points at
    /// the same file, which is why it is used when the real path has one.
    /// </summary>
    private static string ExecutablePathForTor(string path)
    {
        if (!path.Contains(' '))
        {
            return path;
        }

        var buffer = new StringBuilder(1024);
        var length = GetShortPathNameW(path, buffer, (uint)buffer.Capacity);

        if (length > 0 && length < buffer.Capacity)
        {
            var shortPath = buffer.ToString();
            if (!shortPath.Contains(' '))
            {
                Log.App($"Using the short path '{shortPath}' for the pluggable transport");
                return shortPath;
            }
        }

        // 8.3 name generation can be disabled on a volume. Nothing can be done about it here, so
        // say so plainly rather than writing a line that will fail in a confusing way.
        Log.App(
            $"The pluggable transport path '{path}' contains a space and no 8.3 short name is available. " +
            "Bridges will not start. Move the tool to a path without spaces, or clear the PATH entry " +
            "so the bundled copy is used.");

        return path;
    }

    // DllImport rather than LibraryImport: the source generator does not marshal StringBuilder.
    [System.Runtime.InteropServices.DllImport(
        "kernel32.dll",
        CharSet = System.Runtime.InteropServices.CharSet.Unicode,
        SetLastError = true)]
    private static extern uint GetShortPathNameW(
        string lpszLongPath,
        StringBuilder lpszShortPath,
        uint cchBuffer);
}
